//
//  WorkQueueItem.m
//  TiVo Butler
//
//  Created by Eric Baur on 2/7/08.
//  Copyright 2008 Eric Shore Baur. All rights reserved.
//

#import "WorkQueueItem.h"

@implementation WorkQueueItem

- (BOOL)canRemove
{
	if ( [self.active boolValue] ) {
		return NO;
	} else {
		return YES;
	}
}

#pragma mark -
#pragma mark Accessor methods

@dynamic active;
@dynamic addedDate;
@dynamic completedDate;
@dynamic message;
@dynamic sourceName;
@dynamic sourceType;
@dynamic startedDate;
@dynamic savedPath;

@dynamic program;
@dynamic smartGroup;
@dynamic steps;

- (NSNumber *)active
{
	if ( nil==self.completedDate && nil!=self.startedDate )
		return [NSNumber numberWithBool:YES];
	else
		return [NSNumber numberWithBool:NO];
}

- (NSString *)name
{
	if ( nil != self.program) {
		return self.program.title;
	} else {
		return @"";
	}
}

- (void)setSourceType:(NSNumber *)value 
{
	if ( [self.sourceType intValue] ) {
		WARNING( @"attempt to re-set sourceType (blocking)" );
		return;
	}
    [self willChangeValueForKey:@"sourceType"];
    [self setPrimitiveSourceType:value];
    [self didChangeValueForKey:@"sourceType"];
}

#pragma mark -
#pragma mark Transient accessors

- (NSString *)sourceName
{
	int type = [self.sourceType intValue];
	switch (type) {
		case WQAutoGeneratedSourceType:	return WQAutoGeneratedSourceString;	break;
		case WQUserInitSourceType:		return WQUserInitSourceString;		break;
		case WQScheduledSourceType:		return WQScheduledSourceString;		break;
		default:						return nil;
	}
}



@end
