//
//  WorkQueueItem.h
//  TiVo Butler
//
//  Created by Eric Baur on 2/7/08.
//  Copyright 2008 Eric Shore Baur. All rights reserved.
//

#import <Cocoa/Cocoa.h>

#import "EntityHelper.h"

#import "TiVoProgram.h"

@class WorkQueueFile;

typedef enum {
	WQAction_MIN = 0,
	WQNoAction = WQAction_MIN,
	WQDownloadAction,
	WQDecodeAction,
	WQConvertAction,
	WQPostProcessAction,
	WQAction_MAX = WQPostProcessAction
} WQAction;

#define WQNoActionExtension				@""
#define WQDownloadActionExtension		@".tivo"
#define WQDecodeActionExtension			@".mpg"
#define WQConvertActionExtension		@".mp4"
#define WQPostProcessActionExtension	nil

typedef enum {
	WQSourceType_MIN = 0,
	WQAutoGeneratedSourceType = WQSourceType_MIN,
	WQUserInitSourceType,
	WQScheduledSourceType,
	WQSourceType_MAX = WQScheduledSourceType
} WQSourceType;

#define WQAutoGeneratedSourceString	@"Auto Generated"
#define WQUserInitSourceString		@"User Initialized"
#define WQScheduledSourceString		@"Scheduled"

typedef enum {
	WQArgumentSubstitutionValue_MIN = 0,
	WQArgumentNone = WQArgumentSubstitutionValue_MIN,
	WQArgumentMAK,
	WQArgumentInputFile,
	WQArgumentOutputFile,
	WQArgumentSubstitutionValue_MAX = WQArgumentOutputFile
} WQArgumentSubstitutionValue;

@interface WorkQueueItem : NSManagedObject {
	NSURLDownload *programDownload;
	
	int currentActionPercent;
	unsigned long long receivedBytes;
	unsigned long long expectedBytes;
	
	NSTask *queueTask;
	NSFileHandle *queueFileHandle;
}

- (BOOL)canRemove;

@property (retain) NSNumber * actionType;
@property (retain) NSNumber * active;
@property (retain) NSDate * addedDate;
@property (retain) NSDate * completedDate;
@property (retain) NSNumber * shouldKeepInput;
@property (retain) NSString * message;
@property (retain) NSNumber * sourceType;
@property (retain) NSDate * startedDate;
@property (retain) NSString * savedPath;

@property (retain) TiVoProgram * program;
@property (retain) WorkQueueFile * readFile;
@property (retain) WorkQueueFile * writeFile;

- (void)setupWriteFile;

@end

@interface WorkQueueItem (Workflows)

+ (NSDictionary *)workflowDefaults;

- (NSString *)stringForSubstitutionValue:(WQArgumentSubstitutionValue)substitutionValue;

- (void)beginProcessing;

- (void)beginDownload;
//- (void)setupDownloadPath;
- (void)removeFiles;
- (void)completeWithMessage:(NSString *)message;

- (void)beginDecode;
- (void)decodeReadAvailableData:(NSNotification *)notification;
- (void)decoderDidTerminate:(NSNotification *)notification;

- (void)beginConversion;
- (void)convertReadAvailableData:(NSNotification *)notification;
- (void)convertDidTerminate:(NSNotification *)notification;

@end

@interface WorkQueueItem (CoreDataGeneratedPrimitiveAccessors)

- (NSNumber *)primitiveActionType;
- (void)setPrimitiveActionType:(NSNumber *)value;

- (TiVoProgram *)primitiveProgram;
- (void)setPrimitiveProgram:(TiVoProgram *)value;

- (NSNumber *)primitiveSourceType;
- (void)setPrimitiveSourceType:(NSNumber *)value;

@end

#import "WorkQueueFile.h"
